"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['ear_training.py']
# DATA_FILES = []

DATA_FILES = ['C.wav',
              'Db.wav',
              'D.wav',
              'Eb.wav',
              'E.wav',
              'F.wav',
              'Gb.wav',
              'G.wav',
              'Ab.wav',
              'A.wav',
              'Bb.wav',
              'B.wav',
              'Roboto-Condensed.ttf']
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
